export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
          <link href="https://fonts.googleapis.com/css2?family=Coiny&display=swap" rel="stylesheet"/>
      </head>
      <body className="font-[Orbitron]">{children}</body>
    </html>
  )
}
